/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Deployment script for $(SHPURDPDBNAME)

Use this script in sqlcmd mode, with a series of environment variables like this:
set SHPURDPDBNAME=shpurdp
set SHPURDPDBLOGNAME=shpurdp_log

set SHPURDPDBPATH=C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\shpurdp.mdf
set SHPURDPDBLOGPATH=C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\shpurdp_log.ldf

set SHPURDPDBOWNER=hadoop

sqlcmd -S localhost\SQLEXPRESS -i C:\app\shpurdp-server-1.3.0-SNAPSHOT\resources\Shpurdp-DDL-SQLServer-CREATELOCAL.sql
*/

USE [master]
GO

IF db_id('$(SHPURDPDBNAME)') IS NOT NULL
BEGIN
    Print N'Dropping [dbo].[$(SHPURDPDBNAME)] database...'
    ALTER DATABASE [$(SHPURDPDBNAME)] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [$(SHPURDPDBNAME)]
END
GO

Print N'Creating [dbo].[$(SHPURDPDBNAME)] database at $(SHPURDPDBPATH)...'

/****** Object:  Database [$(SHPURDPDBNAME)]    Script Date: 6/11/2014 9:21:53 PM ******/

CREATE DATABASE [$(SHPURDPDBNAME)]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'$(SHPURDPDBNAME)', FILENAME = N'$(SHPURDPDBPATH)' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'$(SHPURDPDBLOGNAME)', FILENAME = N'$(SHPURDPDBLOGPATH)' , SIZE = 1024KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [$(SHPURDPDBNAME)] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET ANSI_NULLS OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET ANSI_PADDING OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET ARITHABORT OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET  DISABLE_BROKER
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET  READ_WRITE
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET RECOVERY SIMPLE
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET  MULTI_USER
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO
ALTER DATABASE [$(SHPURDPDBNAME)] SET DELAYED_DURABILITY = DISABLED
GO

USE [$(SHPURDPDBNAME)]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [$(SHPURDPDBNAME)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

ALTER authorization on DATABASE::$(SHPURDPDBNAME) to [NT AUTHORITY\SYSTEM]
GO

--set SHPURDPDBOWNER=hadoop
if exists (select 1 from master.sys.syslogins where name='$(SHPURDPDBOWNER)')
BEGIN
    CREATE USER [$(SHPURDPDBOWNER)] FOR LOGIN [$(SHPURDPDBOWNER)]
    ALTER ROLE [db_owner] ADD MEMBER [$(SHPURDPDBOWNER)]
END
GO

Print N'[dbo].[$(SHPURDPDBNAME)] database created.'
